#ifndef IDEAL_ORDER_COMPAT_H
#define IDEAL_ORDER_COMPAT_H

/* Source-compatibility header for the pre-0.7 C API. */
#include "monotonic_order.h"

typedef MonotonicOrder IdealOrder;

#define IDEAL_ORDER_API MONOTONIC_ORDER_API
#define ideal_order_create monotonic_order_create
#define ideal_order_destroy monotonic_order_destroy
#define ideal_order_size monotonic_order_size
#define ideal_order_bins monotonic_order_bins
#define ideal_order_storage_bytes monotonic_order_storage_bytes
#define ideal_order_min monotonic_order_min
#define ideal_order_max monotonic_order_max
#define ideal_order_q1 monotonic_order_q1
#define ideal_order_median monotonic_order_median
#define ideal_order_q3 monotonic_order_q3
#define ideal_order_mad monotonic_order_mad
#define ideal_order_rank monotonic_order_rank
#define ideal_order_quantile monotonic_order_quantile
#define ideal_order_rank_array monotonic_order_rank_array
#define ideal_order_sort monotonic_order_sort
#define ideal_order_sort_inplace monotonic_order_sort_inplace
#define ideal_order_is_sorted monotonic_order_is_sorted
#define ideal_order_unique_sorted monotonic_order_unique_sorted
#define ideal_order_argsort_u64 monotonic_order_argsort_u64
#define ideal_order_lexargsort_u64 monotonic_order_lexargsort_u64
#define ideal_order_argsort_bytes monotonic_order_argsort_bytes
#define ideal_order_hilbert2d_u64 monotonic_order_hilbert2d_u64
#define ideal_order_key monotonic_order_key

#endif
